In [2]:
1+1

2

In [1]:
import numpy as np

In [3]:
lst=[1,2,3,4]
arr = np.array(lst)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.shape

(2, 3)

In [11]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
arr1.dtype

dtype('int32')

In [19]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [24]:
np.arange(10,5,2)

array([], dtype=int32)

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [33]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [37]:
np.linspace(1,20,10).reshape(10,1)

array([[ 1.        ],
       [ 3.11111111],
       [ 5.22222222],
       [ 7.33333333],
       [ 9.44444444],
       [11.55555556],
       [13.66666667],
       [15.77777778],
       [17.88888889],
       [20.        ]])

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.ones((4,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
6 + np.ones((3,4))   #Thala for reason

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.identity(5)   #both are same

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [58]:
print("Print random number generation(Uniform distribution ")
np.random.rand(2,3)

Print random number generation(Uniform distribution 


array([[0.37415443, 0.9476435 , 0.77730345],
       [0.78071826, 0.4587121 , 0.46036377]])

In [59]:
print("Random number following a Normal distribtuion with mean=0 and std=1")
np.random.randn(5,3)

Random number following a Normal distribtuion with mean=0 and std=1


array([[-1.10808445e+00, -3.27307685e-01,  7.87404799e-01],
       [ 6.61495748e-01,  2.51372092e-01, -2.45233804e-01],
       [ 8.92170414e-01,  5.51300038e-02,  1.20725214e-01],
       [-8.43771776e-01,  1.37168460e-01, -1.32641597e+00],
       [-1.73382595e+00, -6.91347468e-01,  2.67202120e-04]])

In [60]:
np.random.randint(1,100,20)

array([87, 15, 15, 30, 50, 10, 56, 62, 48, 74, 30, 99, 21, 68, 10, 61, 30,
       98, 86, 43])

In [61]:
np.random.randint(1,100,(4,4))

array([[86, 88, 63, 55],
       [30, 95, 33, 44],
       [75, 80, 18, 31],
       [72, 74, 28, 18]])

In [62]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr = np.arange(0,11)

In [67]:
#Slicing
arr[2:7:2]

array([2, 4, 6])

In [69]:
arr[-1:7:-1]

array([10,  9,  8])

In [72]:
arr1=np.random.randint(2,100,20).reshape(4,5)

In [73]:
arr1

array([[53, 41, 78, 43,  6],
       [ 8, 15, 95, 36, 48],
       [45, 90, 86,  9, 22],
       [20,  4, 34, 73, 13]])

In [74]:
arr1[3:,1:]

array([[ 4, 34, 73, 13]])

In [75]:
arr1[:3,:3]

array([[53, 41, 78],
       [ 8, 15, 95],
       [45, 90, 86]])

In [96]:
## Universal function
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [81]:
arr1

array([[52, 23, 58],
       [38, 76, 95],
       [49, 74, 84]])

In [82]:
arr2

array([[24, 45, 58],
       [41, 33, 50],
       [81, 64, 40]])

In [87]:
arr1 * arr2

array([[1248, 1035, 3364],
       [1558, 2508, 4750],
       [3969, 4736, 3360]])

In [89]:
np.sqrt(arr1)   #it will sqaure root

array([[7.21110255, 4.79583152, 7.61577311],
       [6.164414  , 8.71779789, 9.74679434],
       [7.        , 8.60232527, 9.16515139]])

In [ ]:
arr1[2:]=100

In [91]:
arr1=np.arange(1,10)

In [92]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr1[2:]=100

In [94]:
arr1

array([  1,   2, 100, 100, 100, 100, 100, 100, 100])

In [97]:
np.dot(arr1,arr2)

array([[10617, 16330,  7270],
       [ 5224, 11508,  4748],
       [ 5534, 11436,  4756]])

In [98]:
np.matmul(arr1,arr2)

array([[10617, 16330,  7270],
       [ 5224, 11508,  4748],
       [ 5534, 11436,  4756]])